/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef RTL_DEBUG_PORT_DEF_H
#define RTL_DEBUG_PORT_DEF_H

#ifdef  __cplusplus
extern "C" {
#endif /* __cplusplus */

/*============================================================================*
 *                        Header Files
 *============================================================================*/
#include "utils/rtl_utils.h"
#include "pcc_reg.h"

/*============================================================================*
 *                          Debug Port Defines
 *============================================================================*/
#define DEBUG_PORT_SUPPORT_MULTI_PLATFORM            (0)
#define DEBUG_PORT_SUPPORT_QACTIVE_STATUS            (1)
#define DEBUG_PORT_SUPPORT_AON_DEBUG                 (1)

/*============================================================================*
 *                          Debug Port TYPE
 *============================================================================*/
typedef enum
{
    PCK600_QACTIVE_CORE_DBG_TYPE = 0,
    PCK600_QACTIVE_CORE_LPDQ_OSC_QREQ,
    PCK600_QACTIVE_CORE_LPDQ_OSC_QACCEPT,
    PCK600_QACTIVE_CORE_LPDQ_OSC_QACTIVE_1,
    PCK600_QACTIVE_CORE_LPDQ_OSC_CG,
    PCK600_QACTIVE_CORE_LPDQ_PLL1_1,
    PCK600_QACTIVE_CORE_LPDQ_SDM_QREQ,
    PCK600_QACTIVE_CORE_LPDQ_SDM_QACCEPT,
    PCK600_QACTIVE_CORE_LPDQ_SDM_QACTIVE,
    PCK600_QACTIVE_CORE_LPDQ_XTAL_QREQ,
    PCK600_QACTIVE_CORE_LPDQ_XTAL_QACCEPT,
    PCK600_QACTIVE_CORE_LPDQ_XTAL_QACTIVE_1,
    PCK600_QACTIVE_CORE_LPDQ_XTAL_1,
    PCK600_QACTIVE_CORE_LPDQ_PLATFORM,
    PCK600_QACTIVE_CORE_LPDQ_PLATFORM_QACTIVE,
    PCK600_QACTIVE_CORE_LPDQ_OSC1,
    PCK600_QACTIVE_CORE_LPDQ_VCORE_QREQ,
    PCK600_QACTIVE_CORE_LPDQ_VCORE_QACCEPT,
    PCK600_QACTIVE_CORE_LPDQ_VCORE_QACTIVE_1,
    PCK600_QACTIVE_CORE_LPDQ_VCORE_1_QREQ,
    PCK600_QACTIVE_CORE_LPDQ_VCORE_1_QACCEPT,
    PCK600_QACTIVE_CORE_LPDQ_VCORE_1_QACTIVE,
    PCK600_QACTIVE_CORE_DEVICE2,
    PCK600_QACTIVE_CORE_DEVICE3,
    PCK600_QACTIVE_CORE_DEVICE4,
    PCK600_QACTIVE_CORE_DEVICE5,
    PCK600_QACTIVE_CORE_DEVICE6,
    PCK600_QACTIVE_CORE_DEVICE7,
    PCK600_QACTIVE_CORE_DEVICE_GROUP,
    PCK600_QACTIVE_CORE_DEVICE_POW,
    PCK600_QACTIVE_CORE_LPDQ_OSC,
    PCK600_QACTIVE_CORE_LPDQ_OSC10M,
    PCK600_QACTIVE_CORE_LPDQ_XTAL,
    PCK600_QACTIVE_CORE_DEVICE1,
    PCK600_QACTIVE_CORE_DEVICE0,
    PCK600_QACTIVE_CORE_LPCQ_BT,
    PCK600_QACTIVE_CORE_LPCQ_PLATFORM,
    PCK600_QACTIVE_CORE_CLKCTRL_PPU_VCORE,

    PCK600_QACTIVE_PON_DBG_TYPE = 0x100,
    PCK600_QACTIVE_PON_PPU_VCORE,
    PCK600_QACTIVE_PON_CLK_SOURCE,
    PCK600_QACTIVE_PON_VPON_DEVICE,
    PCK600_QACTIVE_PON_VPON_SCH_PLAN,
    PCK600_QACTIVE_PON_PPU_VCORE_PCSM,
    PCK600_QACTIVE_PON_LPDQ_PPU_VCORE,
    PCK600_QACTIVE_PON_LPDQ_OSC128K_VPON,
    PCK600_QACTIVE_PON_LPDQ_OSC10M_VPON,
    PCK600_QACTIVE_PON_LPDQ_OSC10M_VPON_QACTIVE,
    PCK600_QACTIVE_PON_LPDQ_OSC10M_VPON_HV,
    PCK600_QACTIVE_PON_LPCQ_PLATFORM,
    PCK600_QACTIVE_PON_CLKCTRL_PPU_VCORE,

    PCK600_QACTIVE_AON_DBG_TYPE = 0x1000,
    PCK600_QACTIVE_AON_PPU_VPON,
    PCK600_QACTIVE_AON_PPU_VPON_PCSM,
    PCK600_QACTIVE_AON_PPU_VPON_QACTIVE,
    PCK600_QACTIVE_AON_LPDQ_VPON,
    PCK600_QACTIVE_AON_LPDQ_VPON_QACTIVE_2,
    PCK600_QACTIVE_AON_LPDQ_VPON_QACTIVE_1,
    PCK600_QACTIVE_AON_LPDQ_VPON_QACTIVE_0,
    PCK600_QACTIVE_AON_LPDQ_OSC10M,
    PCK600_QACTIVE_AON_P2Q_OPMODE,
    PCK600_QACTIVE_AON_P2Q_MEMOFF,
    PCK600_QACTIVE_AON_P2Q_ON,
    PCK600_QACTIVE_AON_CLK_SOURCE_VAON
} PCK600_QACTIVE_GROUP_T;

typedef enum
{
    PCK600_QACTIVE_I2S        = 0,
    PCK600_QACTIVE_ADC        = 1,
    PCK600_QACTIVE_UART3      = 2,
    PCK600_QACTIVE_UART2      = 3,
    PCK600_QACTIVE_UART1      = 4,
    PCK600_QACTIVE_UART0      = 5,
    PCK600_QACTIVE_TMETER     = 6,
    PCK600_QACTIVE_TIMER1_CH8 = 7,
    PCK600_QACTIVE_TIMER1_CH7 = 8,
    PCK600_QACTIVE_TIMER1_CH6 = 9,
    PCK600_QACTIVE_TIMER1_CH5 = 10,
    PCK600_QACTIVE_TIMER1_CH4 = 11,
    PCK600_QACTIVE_TIMER1_CH3 = 12,
    PCK600_QACTIVE_TIMER1_CH2 = 13,
    PCK600_QACTIVE_TIMER1_CH1 = 14,
    PCK600_QACTIVE_TIMER1_CH0 = 15,
    PCK600_QACTIVE_TIMER0_CH1 = 16,
    PCK600_QACTIVE_TIMER0_CH0 = 17,
    PCK600_QACTIVE_SPI3W      = 18,
    PCK600_QACTIVE_SPI2       = 19,
    PCK600_QACTIVE_SPI1       = 20,
    PCK600_QACTIVE_SPI0       = 21,
    PCK600_QACTIVE_KEYSCAN    = 22,
    PCK600_QACTIVE_IR         = 23,
    PCK600_QACTIVE_I2C1       = 24,
    PCK600_QACTIVE_I2C0       = 25,
    PCK600_QACTIVE_GPIO       = 26,
    PCK600_QACTIVE_DMA        = 27,
    PCK600_QACTIVE_TIMER2_CH0 = 28,
    PCK600_QACTIVE_CAN        = 29,
    PCK600_QACTIVE_USB        = 30,

    PCK600_QACTIVE_RFC        = 31,
    PCK600_QACTIVE_PRO24G     = 32,
    PCK600_QACTIVE_PCC        = 33,
    PCK600_QACTIVE_MODEM      = 34,
    PCK600_QACTIVE_CAL80M     = 35,
    PCK600_QACTIVE_CAL32K     = 36,
    PCK600_QACTIVE_CAL10M     = 37,
    PCK600_QACTIVE_BTMAC      = 38,
    PCK600_QACTIVE_BT_VEN     = 39,
    PCK600_QACTIVE_AUDIO      = 40,
    PCK600_QACTIVE_AACK       = 41,
    PCK600_QACTIVE_AES        = 42,
    PCK600_QACTIVE_SHA256     = 43,
    PCK600_QACTIVE_CPU        = 44,
    PCK600_QACTIVE_SPIC0      = 45,
    PCK600_QACTIVE_RNG        = 46,
    PCK600_QACTIVE_VDREG      = 47,

    PCK600_QACTIVE_DEVICE_MAX,

} PCK600_QACTIVE_DEVICE_T;

typedef enum
{
    DEBUG_PCK600_OUTPUT_TO_VPON_PPU          = ((14 << 7) | 0),
    DEBUG_PCK600_OUTPUT_TO_VCORE_PPU         = ((14 << 7) | 1),
} AON_DEBUG_PORT;

#ifdef  __cplusplus
}
#endif /* __cplusplus */

#endif /* RTL_DEBUG_PORT_DEF_H */
